openapi: 3.0.3
info:
  title: "{{ .AppName }}"
  version: "{{ .AppVersion }}"
paths:
  /register:
    post:
      summary: Register new user
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegisterResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponseError'
              example:
                error: user 'User' is already exists
          description: Bad request
  /login:
    post:
      summary: Login user (get JWT token)
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLoginResponseError'
              example:
                error: No user with name 'User'
          description: Bad request
  /users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllUsersResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllUsersResponseError'
              example:
                error: no users
          description: Bad request
  /users/{id}:
    get:
      summary: Get user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserByIDResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserByIDResponseError'
              example:
                error: No user with id '1'
          description: Bad request
    put:
      summary: Update user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserByIDRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserByIDResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateUserByIDResponseError'
              example:
                error: No user with id '1'
          description: Bad request
    delete:
      summary: Delete user by id
      tags:
        - Users
      parameters:
        - name: id
          in: path
          description: ID of user
          required: true
          schema:
            type: integer
            format: int
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUserResponse'
          description: Success request
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteUserResponseError'
              example:
                error: No user with id '1'
          description: Bad request
components:
  schemas:
    UserRegister:
      additionalProperties: false
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UserRegisterResponse:
      type: object
      properties:
        Created new user 'User' with id:
          type: string
      required:
        - Created new user 'User' with id
    UserResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    UserLogin:
      additionalProperties: false
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UserLoginResponse:
      type: object
      properties:
        token:
          type: string
      required:
        - token
    UserLoginResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    GetAllUsersResponse:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          username:
            type: string
        required:
          - id
          - username
    GetAllUsersResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    GetUserByIDResponse:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
      required:
        - id
        - username
    GetUserByIDResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    UpdateUserByIDRequest:
      additionalProperties: false
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    UpdateUserByIDResponse:
      type: object
      properties:
        Updated user with id:
          type: string
      required:
        - Updated user with id
    UpdateUserByIDResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
    DeleteUserResponse:
      type: object
      properties:
        Deleted user with id:
          type: string
      required:
        - Deleted user with id
    DeleteUserResponseError:
      type: object
      properties:
        error:
          type: string
      required:
        - error
