postgres:
  host: database
  port: 5432
  username: pg
  dbName: crud
  sslMode: disable
app:
  port: 8000
  maxHeaderBytes: 20
  writeTimeout: 10
  readTimeout: 10
logger:
  logLevel: 0 #0 - info, 2 - error