version: "3.8"

services:
  go-service:
    container_name: go-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: