version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
#    command: ./wait-for-postgres.sh database ./service
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgres:latest
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

# method for starting database migrations from a container
#  migrations:
#    container_name: migrations
#    image: migrate/migrate
#    command:
#      [ "-path", "/migrations", "-database",  "postgres://pg:pass@database:5432/crud?sslmode=disable", "up" ]
#    depends_on:
#      - database
#    volumes:
#      - ./migrations:/migrations

volumes:
  db: