version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - go-service

  go-service:
    container_name: go-service
    build:
      context: .
      dockerfile: Dockerfile
#    command: ./wait-for-postgres.sh database ./service
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  migrate:
    container_name: migrations
    image: migrate/migrate
    command:
      [ "-path", "/migrations", "-database",  "postgres://pg:pass@database:5432/crud?sslmode=disable", "up" ]
    depends_on:
      - database
    volumes:
      - ./migrations:/migrations

volumes:
  db: