name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2

      - name: Generate coverage report
        run: |
          go test ./... -coverprofile=coverage.out -covermode=atomic
          go tool cover -func coverage.out

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Run Lints
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1